version: "3.9"
services:

  mongodb:
    image: mongo
    container_name: mongodb-asgard
    environment:
      - MONGO_INITDB_DATABASE=admin
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
    ports:
      - "27018:27017"

  mongo-express:
    image: mongo-express
    container_name: mongo-express-asgard
    restart: always
    ports:
      - "8088:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
      - ME_CONFIG_MONGODB_SERVER=mongodb

  eureka-server:
    image: eureka-server
    ports:
      - "8761:8761"
    restart: unless-stopped

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    restart: unless-stopped

networks:
  default:
    name: asgard