version: "3.9"
services:

  catalog-service:
    image: catalog-service
    container_name: catalog-service
    ports:
      - "8081:8081"
    restart: unless-stopped

  series-service:
    image: series-service
    container_name: series-service
    ports:
      - "8086:8086"
    restart: unless-stopped

  movie-service:
    image: movie-service
    container_name: movie-service
    ports:
      - "8084:8084"
    restart: unless-stopped

networks:
  default:
    name: asgard
