version: "3.9"
services:

  config-server:
    image: config-server
    container_name: config-server
    ports:
      - "8888:8888"
    restart: unless-stopped

  api-gateway:
    image: api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    restart: unless-stopped

networks:
  default:
    name: asgard