version: "3.9"
services:

  config-service:
    image: config-service
    ports:
      - "8888:8888"
    restart: unless-stopped

  api-gateway:
    image: api-gateway
    ports:
      - "8080:8080"
    restart: unless-stopped

networks:
  default:
    name: asgard