version: "3.9"
services:

  series-service:
    image: series-service
    ports:
      - "8086:8086"
    restart: unless-stopped

  movie-service:
    image: movie-service
    ports:
      - "8082:8082"
    restart: unless-stopped

networks:
  default:
    name: asgard
