server:
  port: 8082

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql-movie:3310/movie
    username: root
    password: 1234

  sql:
    init:
      data-locations: classpath:movie.sql

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop

info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
    description: Movie Microservice
