server:
  port: 8086
  
spring:
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: series
      port: 27019
      host: mongodb_series

info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
    description: Series Microservice
